language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"

install:
    - pip install coverage --use-mirrors
    - pip install cython --use-mirrors
    - python setup.py build_ext --inplace

script:
    - nosetests --with-doctest

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install coveralls --use-mirrors ; coveralls ; fi

notifications:
  email: false
